# Generated by Django 2.2.17 on 2021-04-18 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="My_Model",
            fields=[
                (
                    "source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=300,
                        null=True,
                        verbose_name="source",
                    ),
                ),
                (
                    "lastmodified",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="last modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=300,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "charfield",
                    models.CharField(
                        blank=True,
                        help_text="A sample character field",
                        max_length=300,
                        null=True,
                        verbose_name="charfield",
                    ),
                ),
                (
                    "booleanfield",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        help_text="A sample boolean field",
                        verbose_name="booleanfield",
                    ),
                ),
                (
                    "decimalfield",
                    models.DecimalField(
                        decimal_places=8,
                        default="0.00",
                        help_text="A sample decimal field",
                        max_digits=20,
                        verbose_name="decimalfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "my model",
                "verbose_name_plural": "my models",
                "db_table": "my_model",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
